import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // ── Primary: Amber ───────────────────────────────────────────────────
        primary: {
          DEFAULT: '#E8893A',
          light: '#F4A85C',
          dark: '#C96E22',
          foreground: '#FFFFFF',
          hover: '#C96E22',
          focus: 'rgba(232,137,58,0.1)',
        },
        // ── Dark sidebar: Navy ───────────────────────────────────────────────
        sidebar: {
          bg: '#0E1628',
          surface: '#1A2744',
          border: '#1A2744',
          text: '#EEF0F3',
          muted: 'rgba(255,255,255,0.35)',
          'active-bg': 'rgba(232,137,58,0.12)',
          'active-text': '#E8893A',
          hover: '#1A2744',
        },
        // ── Backgrounds ──────────────────────────────────────────────────────
        background: {
          main: '#FAF8F4',
          sidebar: '#FFFFFF',
          card: '#FFFFFF',
          elevated: '#FFFFFF',
          hover: '#F0EDE7',
          selected: 'rgba(232,137,58,0.08)',
        },
        surface: {
          DEFAULT: '#FFFFFF',
          50: '#FAF8F4',
          100: '#F0EDE7',
          muted: '#FAF8F4',
        },
        // ── Text ─────────────────────────────────────────────────────────────
        text: {
          primary: '#1C1917',
          secondary: '#6B6560',
          tertiary: '#9E9894',
          disabled: '#C2BFBA',
          onPrimary: '#FFFFFF',
          label: '#6B6560',
        },
        // ── Borders ──────────────────────────────────────────────────────────
        border: {
          light: '#EAE7E2',
          DEFAULT: '#E0DDD8',
          medium: '#E0DDD8',
          dark: '#C2BFBA',
          focus: '#E8893A',
        },
        // ── Semantic status ───────────────────────────────────────────────────
        status: {
          success: '#2AB27B',
          warning: '#E8893A',
          error: '#E04444',
          info: '#2196F3',
          positive: '#2AB27B',
          negative: '#E04444',
        },
        success: {
          DEFAULT: '#2AB27B',
          foreground: '#FFFFFF',
          muted: 'rgba(42,178,123,0.1)',
        },
        error: {
          DEFAULT: '#E04444',
          foreground: '#FFFFFF',
          muted: 'rgba(224,68,68,0.08)',
        },
        warning: {
          DEFAULT: '#E8893A',
          foreground: '#FFFFFF',
          muted: 'rgba(232,137,58,0.1)',
        },
        muted: {
          DEFAULT: '#6B6560',
          foreground: '#9E9894',
        },
        badge: {
          amber: '#E8893A',
          red: '#E04444',
          blue: '#2196F3',
          green: '#2AB27B',
          gray: '#6B6560',
          black: '#1C1917',
        },
        stat: {
          positive: '#2AB27B',
          negative: '#E04444',
          neutral: '#9E9894',
        },
        chart: {
          primary: '#E8893A',
          secondary: '#2AB27B',
          tertiary: '#2196F3',
          quaternary: '#0E1628',
          grid: '#F0EDE7',
          axis: '#E0DDD8',
        },
      },
      // ── Fonts ────────────────────────────────────────────────────────────────
      fontFamily: {
        sans: ['var(--font-inter)', 'Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        display: ['var(--font-syne)', 'Syne', 'sans-serif'],
        mono: ['var(--font-jetbrains-mono)', 'JetBrains Mono', 'Courier New', 'monospace'],
      },
      fontSize: {
        xs:      ['0.75rem',   { lineHeight: '1.3'  }],
        sm:      ['0.875rem',  { lineHeight: '1.45' }],
        base:    ['1rem',      { lineHeight: '1.55' }],
        md:      ['1.0625rem', { lineHeight: '1.5'  }],
        lg:      ['1.125rem',  { lineHeight: '1.45' }],
        xl:      ['1.25rem',   { lineHeight: '1.4'  }],
        '2xl':   ['1.5rem',    { lineHeight: '1.35' }],
        '3xl':   ['2rem',      { lineHeight: '1.2'  }],
        '4xl':   ['2.5rem',    { lineHeight: '1.15' }],
        '5xl':   ['3rem',      { lineHeight: '1.1'  }],
        display: ['2.25rem',   { lineHeight: '1.2'  }],
      },
      fontWeight: {
        light:     '300',
        normal:    '400',
        medium:    '500',
        semibold:  '600',
        bold:      '700',
        extrabold: '800',
      },
      lineHeight: {
        tight:   '1.25',
        snug:    '1.375',
        normal:  '1.5',
        relaxed: '1.625',
        loose:   '2',
      },
      spacing: {
        xs:  '4px',
        sm:  '8px',
        md:  '12px',
        lg:  '16px',
        xl:  '20px',
        '2xl': '24px',
        '3xl': '32px',
        '4xl': '40px',
        '5xl': '48px',
        cardPadding:     '20px',
        cardPaddingLg:   '24px',
        sidebarPadding:  '16px 12px',
        sectionGap:      '20px',
        gridGap:         '16px',
        itemGap:         '8px',
        inlineGap:       '12px',
        sidebarWidth:    '240px',
        headerHeight:    '64px',
        bottomNavHeight: '64px',
      },
      borderRadius: {
        DEFAULT: '8px',
        lg:    '12px',
        xl:    '16px',
        '2xl': '20px',
        pill:  '12px',
        full:  '9999px',
      },
      boxShadow: {
        subtle:           '0 1px 3px rgba(0,0,0,0.04)',
        card:             '0 1px 3px rgba(0,0,0,0.04)',
        elevated:         '0 4px 16px rgba(0,0,0,0.08)',
        dropdown:         '0 4px 16px rgba(0,0,0,0.08)',
        fab:              '0 4px 16px rgba(232,137,58,0.35)',
        stat:             '0 2px 8px rgba(0,0,0,0.06)',
        'sidebar-active': 'inset 3px 0 0 #E8893A',
        'amber-glow':     '0 4px 20px rgba(232,137,58,0.3)',
        bottomnav:        '0 -1px 0 #E0DDD8, 0 -8px 24px rgba(0,0,0,0.06)',
        'inner-sm':       'inset 0 1px 2px rgba(0,0,0,0.06)',
      },
      transitionDuration: {
        DEFAULT: '200ms',
        slow: '300ms',
        fast: '150ms',
      },
      transitionTimingFunction: {
        DEFAULT: 'ease',
        spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      keyframes: {
        'fade-up': {
          '0%':   { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          '0%':   { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'slide-in-right': {
          '0%':   { opacity: '0', transform: 'translateX(-8px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'pulse-dot': {
          '0%, 100%': { transform: 'scale(1)',   opacity: '1'   },
          '50%':      { transform: 'scale(1.4)', opacity: '0.7' },
        },
        'skeleton-shimmer': {
          '0%':   { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0'  },
        },
        'spin': {
          '0%':   { transform: 'rotate(0deg)'   },
          '100%': { transform: 'rotate(360deg)' },
        },
        'bounce-in': {
          '0%':   { opacity: '0', transform: 'scale(0.9)' },
          '60%':  {               transform: 'scale(1.02)' },
          '100%': { opacity: '1', transform: 'scale(1)'   },
        },
        'setup-glow': {
          '0%, 100%': { boxShadow: '0 1px 3px rgba(0,0,0,0.04)' },
          '50%':      { boxShadow: '0 1px 3px rgba(0,0,0,0.04), 0 0 0 3px rgba(232,137,58,0.22), 0 0 20px rgba(232,137,58,0.12)' },
        },
      },
      animation: {
        'fade-up':    'fade-up 0.4s ease forwards',
        'fade-up-1':  'fade-up 0.4s ease 60ms forwards',
        'fade-up-2':  'fade-up 0.4s ease 120ms forwards',
        'fade-up-3':  'fade-up 0.4s ease 180ms forwards',
        'fade-up-4':  'fade-up 0.4s ease 240ms forwards',
        'fade-in':    'fade-in 0.3s ease forwards',
        'slide-in':   'slide-in-right 0.25s ease forwards',
        'pulse-dot':  'pulse-dot 2s ease-in-out infinite',
        'spin':       'spin 0.8s linear infinite',
        'bounce-in':  'bounce-in 0.35s ease forwards',
        'setup-glow': 'setup-glow 2.8s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
export default config;
